// backend/schemas/invite.schema.ts
// Based on Product Decisions:
// - Generated by: Room owner + moderators
// - Expiry: 24h, 7 days, or 30 days with configurable max uses
// - Access: Registered users only
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type InviteDocument = Invite & Document & {
  createdAt: Date;
  updatedAt: Date;
};

@Schema({ timestamps: true })
export class Invite {
  @Prop({ required: true, unique: true, index: true })
  code: string; // Random invite code (e.g., "abc123xyz")

  @Prop({ required: true, index: true })
  roomId: string; // Room this invite is for

  @Prop({ required: true })
  roomName: string; // For easy display

  @Prop({ required: true })
  createdBy: string; // Username of creator (owner/moderator)

  @Prop({ required: true })
  expiresAt: Date; // When this invite expires

  @Prop({ type: Number })
  maxUses?: number; // Optional: limit number of uses (undefined = unlimited)

  @Prop({ type: Number, default: 0 })
  currentUses: number; // How many times it's been used

  @Prop({ type: [String], default: [] })
  usedBy: string[]; // List of usernames who used this invite

  @Prop({ default: true })
  isActive: boolean; // Can be manually deactivated

  @Prop({ type: String })
  description?: string; // Optional: "Event invite" or "Friends only"
}

export const InviteSchema = SchemaFactory.createForClass(Invite);

// Indexes
InviteSchema.index({ code: 1 });
InviteSchema.index({ roomId: 1, isActive: 1 });
InviteSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 }); // TTL index

// Helper method to check if invite is valid
InviteSchema.methods.isValid = function (): boolean {
  const now = new Date();

  // Check if expired
  if (this.expiresAt < now) {
    return false;
  }

  // Check if still active
  if (!this.isActive) {
    return false;
  }

  // Check if max uses reached
  if (this.maxUses && this.currentUses >= this.maxUses) {
    return false;
  }

  return true;
};