// backend/invite/invite.service.ts
// Based on Product Decisions:
// - Generated by: Room owner + moderators
// - Expiry: 24h, 7 days, or 30 days with configurable max uses
// - Access: Registered users only
import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Invite, InviteDocument } from '../schemas/invite.schema';
import { Room, RoomDocument } from '../schemas/room.schema';
import * as crypto from 'crypto';

export type InviteDuration = '24h' | '7d' | '30d';

@Injectable()
export class InviteService {
  constructor(
    @InjectModel(Invite.name) private inviteModel: Model<InviteDocument>,
    @InjectModel(Room.name) private roomModel: Model<RoomDocument>,
  ) { }

  // Generate a random invite code
  private generateInviteCode(): string {
    return crypto.randomBytes(6).toString('base64url'); // e.g., "abc123XYZ"
  }

  // Calculate expiry date from duration
  private calculateExpiryDate(duration: InviteDuration): Date {
    const now = new Date();
    switch (duration) {
      case '24h':
        return new Date(now.getTime() + 24 * 60 * 60 * 1000);
      case '7d':
        return new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
      case '30d':
        return new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    }
  }

  // Check if user can create invites (owner or moderator)
  private async canCreateInvite(
    roomName: string,
    username: string
  ): Promise<boolean> {
    const room = await this.roomModel.findOne({ name: roomName });
    if (!room) return false;

    return (
      room.createdBy === username ||
      room.moderators?.includes(username)
    );
  }

  // Create an invite link
  async createInvite(
    roomName: string,
    createdBy: string,
    duration: InviteDuration,
    maxUses?: number,
    description?: string
  ): Promise<InviteDocument> {
    // Verify room exists
    const room = await this.roomModel.findOne({ name: roomName });
    if (!room) {
      throw new Error('Room not found');
    }

    // Verify user has permission
    const canCreate = await this.canCreateInvite(roomName, createdBy);
    if (!canCreate) {
      throw new Error('Only room owner and moderators can create invites');
    }

    // Generate unique code
    let code = this.generateInviteCode();
    let existing = await this.inviteModel.findOne({ code });

    // Ensure unique code
    while (existing) {
      code = this.generateInviteCode();
      existing = await this.inviteModel.findOne({ code });
    }

    // Create invite
    const invite = new this.inviteModel({
      code,
      roomId: room._id.toString(),
      roomName: room.name,
      createdBy,
      expiresAt: this.calculateExpiryDate(duration),
      maxUses,
      description,
      isActive: true,
      currentUses: 0,
      usedBy: [],
    });

    return await invite.save();
  }

  // Get invite by code
  async getInvite(code: string): Promise<InviteDocument | null> {
    return await this.inviteModel.findOne({ code }).exec();
  }

  // Use an invite (registered users only)
  async useInvite(
    code: string,
    username: string
  ): Promise<{ success: boolean; roomName?: string; error?: string }> {
    const invite = await this.getInvite(code);

    if (!invite) {
      return { success: false, error: 'Invalid invite code' };
    }

    // Check if valid using the schema method
    if (!(invite as any).isValid()) {
      return { success: false, error: 'This invite has expired or is no longer valid' };
    }

    // Check if user already used this invite
    if (invite.usedBy.includes(username)) {
      return { success: false, error: 'You have already used this invite' };
    }

    // Add user to room
    const room = await this.roomModel.findById(invite.roomId);
    if (!room) {
      return { success: false, error: 'Room no longer exists' };
    }

    // Add to room members
    if (!room.members?.includes(username)) {
      room.members = [...(room.members || []), username];
      await room.save();
    }

    // Update invite usage
    invite.currentUses += 1;
    invite.usedBy.push(username);

    // Auto-deactivate if max uses reached
    if (invite.maxUses && invite.currentUses >= invite.maxUses) {
      invite.isActive = false;
    }

    await invite.save();

    return { success: true, roomName: room.name };
  }

  // Get all invites for a room
  async getRoomInvites(roomName: string): Promise<InviteDocument[]> {
    return await this.inviteModel
      .find({ roomName, isActive: true })
      .sort({ createdAt: -1 })
      .exec();
  }

  // Deactivate an invite
  async deactivateInvite(code: string, username: string): Promise<boolean> {
    const invite = await this.getInvite(code);
    if (!invite) return false;

    // Only creator or room owner/moderator can deactivate
    const canDeactivate = await this.canCreateInvite(invite.roomName, username);
    if (!canDeactivate && invite.createdBy !== username) {
      throw new Error('You do not have permission to deactivate this invite');
    }

    invite.isActive = false;
    await invite.save();
    return true;
  }

  // Delete an invite
  async deleteInvite(code: string, username: string): Promise<boolean> {
    const invite = await this.getInvite(code);
    if (!invite) return false;

    // Only creator or room owner/moderator can delete
    const canDelete = await this.canCreateInvite(invite.roomName, username);
    if (!canDelete && invite.createdBy !== username) {
      throw new Error('You do not have permission to delete this invite');
    }

    await this.inviteModel.deleteOne({ code });
    return true;
  }

  // Get invites created by a user
  async getUserInvites(username: string): Promise<InviteDocument[]> {
    return await this.inviteModel
      .find({ createdBy: username })
      .sort({ createdAt: -1 })
      .exec();
  }

  // Cleanup expired invites (run as cron job)
  async cleanupExpiredInvites(): Promise<number> {
    const result = await this.inviteModel.deleteMany({
      expiresAt: { $lt: new Date() },
    });
    return result.deletedCount;
  }

  // Get invite statistics
  async getInviteStats(code: string): Promise<{
    code: string;
    room: string;
    uses: number;
    maxUses?: number;
    expiresAt: Date;
    isActive: boolean;
    usedBy: string[];
  } | null> {
    const invite = await this.getInvite(code);
    if (!invite) return null;

    return {
      code: invite.code,
      room: invite.roomName,
      uses: invite.currentUses,
      maxUses: invite.maxUses,
      expiresAt: invite.expiresAt,
      isActive: invite.isActive,
      usedBy: invite.usedBy,
    };
  }
}